### ISSUE TITLE
LSP not starting after upgrade

### ISSUE THREAD

**Issue by unrooot** [lopi-py/luau-lsp.nvim#26]
Hi,

After upgrading to the latest release of neovim (0.10.1) and luau-lsp (1.5.0) it appears the LSP isn't loading anymore. `:LspLog` is empty, and `:checkhealth luau-lsp` reports no issues. I'm on macOS Sonoma 14.5.

`:LspInfo` results:
![CleanShot 2024-08-14 at 23 17 01@2x](https://github.com/user-attachments/assets/29628b11-3611-4377-8597-06b4088d1b86)

![CleanShot 2024-08-14 at 23 18 03@2x](https://github.com/user-attachments/assets/3ad29ce6-4aea-4678-aa23-ff6c7fef23f4)

This is my config:
```lua
local mason = require("mason")
local mason_lsp_config = require("mason-lspconfig")
local lsp_config = require("lspconfig")

mason.setup()

mason_lsp_config.setup_handlers({
    -- this function only prints eslint/tsserver, i still have the same problem
    -- if I remove it (added caveat just since there's a warning specifically
    -- about not calling `lspconfig.luau_lsp.setup`)
    function(name)
        lsp_config[name].setup({
            capabilities = capabilities,
            format = {
                indent_style = "tab",
                tab_width = "4",
                quote_style = "double",
            },
            on_attach = onAttach,
        })
    end,

    luau_lsp = function()
        require("luau-lsp").setup({
            platform = {
                type = "roblox"
            },
            types = {
                roblox_security_level = "PluginSecurity",
            },
            server = {
                capabilities = require("cmp_nvim_lsp").default_capabilities(),
                filetypes = { "lua", "luau" },
                settings = {
                    ["luau-lsp"] = {
                        completion = {
                            imports = {
                                enabled = true,
                            }
                        },
                    },
                },
                on_attach = onAttach,
            },
            sourcemap = {
                enabled = false,
                autogenerate = false,
            },
        })
    end,
})
```

I've been reading through the documentation for this plugin, the luau-lsp repo, and Mason and can't seem to figure out what I'm doing wrong. I can't get it to work either with a minimal configuration like on the README. This is the same configuration I was using before updating, except for adding the platform/types tables.

Thanks!

**Comment by lopi-py** [comment]
Do you get any message like "client exited with signal..." after opening a luau file?

Did you try opening a `.lua` or `.luau` file? If it was .lua, it wouldn't work (filetypes setting is not respected anymore), if you really want to use luau lsp for lua files, theres a snippet for that in the FAQ section of the readme

I've heard luau-lsp 1.32.3 is not working for some people (it does for me), so try downgrading the luau lsp version (`:MasonInstall luau-lsp@1.32.1`)

**Comment by unrooot** [comment]
I didn't get anything like that, but I was able to confirm that the `luau_lsp` function in the handlers table was running by adding some prints. I did try opening a `.luau` file, also `.lua` with the snippet you're referring to added to the bottom of the same file as the rest of the config ... downgrading the version of luau-lsp with Mason didn't seem to affect anything either, but I was able to pin the version of luau-lsp.nvim to 1.4.0 through lazy and got it working again that way

**Comment by lopi-py** [comment]
Have you tried using the latest commit? For full lsp logs you need to add `vim.lsp.set_log_level(vim.log.levels.TRACE)` to your config.

Can you also please try this minimal init.lua? It will use the latest commit
```lua
for _, url in pairs {
  "https://github.com/nvim-lua/plenary.nvim",
  "https://github.com/lopi-py/luau-lsp.nvim",
  "https://github.com/williamboman/mason.nvim",
  "https://github.com/williamboman/mason-lspconfig.nvim",
  -- add other plugins if necessary
} do
  local path = vim.fs.joinpath(vim.fn.stdpath "cache", "luau-lsp.nvim-issue", vim.fs.basename(url))
  if not vim.uv.fs_stat(path) then
    vim.system({ "git", "clone", "--depth=1", url, path }):wait()
  end
  vim.opt.rtp:append(path)
end

require("mason").setup()
require("mason-lspconfig").setup { ensure_installed = { "luau_lsp" } }

require("luau-lsp").setup {
  -- add your config options
}
```
1. `nvim -u minimal.lua`
2. `:e path/to/your/file.luau`

You can use neovim's built-in autocompletion by pressing `ctrl+x` + `ctrl+o` in insert mode, just wait a few seconds to the server can load.

It works as intended for me

**Comment by jaschutte** [comment]
I too can confirm it does not start. I've used the minimal.lua example you showed and it gives me the same error as my regular setup.

![image](https://github.com/user-attachments/assets/fa601afa-3730-43ac-af48-404217538918)

The luau-lsp executable is in path. If I print the output of: `:lua print(vim.lsp.start_client({cmd = {"luau-lsp", "lsp"}}))` I get `2, nil`, `3, nil` etc. So I assume some of the default options may cause something to break.

**Comment by lopi-py** [comment]
@jaschutte That error message is a bit outdated, it was changed 3 days ago, are you using mason by any chance? I suspect this problem is because luau-lsp is loading *before* mason

**Comment by jaschutte** [comment]
> @jaschutte That error message is a bit outdated, it was changed 3 days ago, are you using mason by any chance? I suspect this problem is because luau-lsp is loading *before* mason

This loaded from `nvim -u minimal` provided by you. On my own config I do not use meson.

I encountered the modern equivalent error on the latest git versions too. With my own and minimal config.

I also tried using luau-lsp 1.32.1, also to no avail

**Comment by lopi-py** [comment]
@jaschutte Can you please try the latest commit? I managed to get some repro for "executable not found" but it is fixed in the latest commit

**Comment by jaschutte** [comment]
> @jaschutte Can you please try the latest commit? I managed to get some repro for "executable not found" but it is fixed in the latest commit

I will try it soon, I'll follow up in 30min-ish

**Comment by jaschutte** [comment]
@lopi-py 
Still getting the error `[luau-lsp.nvim] luau-lsp executable not found`

**Comment by lopi-py** [comment]
@jaschutte what is the output for `:checkhealth luau-lsp` and `:lua print(vim.fn.exepath("luau-lsp"))`?

**Comment by jaschutte** [comment]
![image](https://github.com/user-attachments/assets/e98e71a4-e9a8-4a62-8de5-4d947f085648)

Rojo has nothing to do with this, I got the error even in an environment with Rojo installed.

As for `:lua print(vim.fn.exepath("luau-lsp"))`
It prints out `/run/current-system/sw/bin/luau-lsp`, which is a symlink to the luau-lsp executable

**Comment by lopi-py** [comment]
What if you try using an executable instead of a symlink? I tried removing mason and I got "executable not found" but when I installed luau-lsp externally (using aftman) it started to work again

**Comment by jaschutte** [comment]
That's just really possible on NixOS, although even when I provided the path directly to the executable I don't recall it working, but I can try again with the latest git

**Comment by jaschutte** [comment]
I'm going to hack a bit with a local clone I made of the repo, i'll keep you up to date if I find something which works.

**Comment by lopi-py** [comment]
What is strange is that the health check is working, but it's the same command

**Comment by lopi-py** [comment]
@jaschutte https://github.com/lopi-py/luau-lsp.nvim/blob/727ec513b446f471dc65356de1f7331cb18b4fa7/lua/luau-lsp/server.lua#L141 has a second return which is the error if starting the server has failed

**Comment by jaschutte** [comment]
> @jaschutte
> 
> https://github.com/lopi-py/luau-lsp.nvim/blob/727ec513b446f471dc65356de1f7331cb18b4fa7/lua/luau-lsp/server.lua#L141
> has a second return which is the error if starting the server has failed

Ohh, good one, let me check it out

**Comment by jaschutte** [comment]
Got the error: `luau-lsp.nvim] luau-lsp executable not found, reason: ...ovim-unwrapped-0.10.1/share/nvim/runtime/lua/vim/uri.lua
:63: attempt to index local 'path' (a function value)`

**Comment by lopi-py** [comment]
Interesting, I just tried and it happens when I pass a function in `root_dir` to `vim.lsp.start_client` instead of a string, but the plugin should convert the `root_dir` function into string, can you show your `luau-lsp.nvim` setup?

**Comment by jaschutte** [comment]
Okay I changed the main source to:
```
  local client_id, fail_reason = vim.lsp.start_client({cmd = {"luau-lsp", "lsp"}})
  if not client_id then
    log.error("luau-lsp executable not found, reason: " .. fail_reason)
    return
  end
```

And now it runs fine, this gives me the impression that it's indeed the default arguments

**Comment by lopi-py** [comment]
It works for me with `minimal_init.lua`, but I feel like it's something related to my previous comment

**Comment by jaschutte** [comment]
> Interesting, I just tried and it happens when I pass a function in `root_dir` to `vim.lsp.start_client` instead of a string, but the plugin should convert the `root_dir` function into string, can you show your `luau-lsp.nvim` setup?

```lua
require("luau-lsp").setup({
    platform = {
        type = "roblox",
    },
    types = {
        roblox_security_level = "None",
    },
    sourcemap = {
        enabled = true,
        autogenerate = true,
        rojo_project_file = "default.project.json",
    },
})
```

**Comment by lopi-py** [comment]
Uh, strange. The error may be here: https://github.com/lopi-py/luau-lsp.nvim/blob/727ec513b446f471dc65356de1f7331cb18b4fa7/lua/luau-lsp/server.lua#L133
Can you make sure that `opts.root_dir` is a string and not a function?

**Comment by jaschutte** [comment]
> Uh, strange. The error may be here:
> 
> https://github.com/lopi-py/luau-lsp.nvim/blob/727ec513b446f471dc65356de1f7331cb18b4fa7/lua/luau-lsp/server.lua#L133
> 
> Can you make sure that `opts.root_dir` is a string and not a function?

Just did, I added
```lua
if type(opts.root_dir) == "function" then
  opts.root_dir = opts.root_dir()
end
```

Right infront of the start_client, and it works fine now!

**Comment by lopi-py** [comment]
Ok, it sounds like it *should* be the fix, but why it only happens to you and not me even with the same commit?

**Comment by jaschutte** [comment]
*no clue!*

**Comment by lopi-py** [comment]
`get_root_dir()` should return a string, so it will be force-merged with the options passed by the user

**Comment by lopi-py** [comment]
> Perhaps I'm on a different version of neovim, which results in the error happening for me?

I'm using 10.0.1 (and I *think* you too?)

**Comment by jaschutte** [comment]
Yeah me too.

Could it be because the default root_dir is a function?
```lua
    root_dir = function(path)
      local server = require "luau-lsp.server"
      return server.root(path, function(name)
        return name:match ".*%.project.json$"
      end) or server.root(path, {
        ".git",
        ".luaurc",
        "stylua.toml",
        "selene.toml",
        "selene.yml",
      })
    end,

```

but then you'd get the error too...?

**Comment by lopi-py** [comment]
I just realized... that it happens if the function returns nil... so `function` force merged with `nil` will result in `function`

**Comment by jaschutte** [comment]
That sounds like it! I've been testing in an environment without any root_dir (just a single main.luau file), so it's been returning nil the entire time, and thus the function.

**Comment by jaschutte** [comment]
simply adding `or vim.fn.getcwd()` resolved the issue as well as being a sensible fallback.

**Comment by lopi-py** [comment]
@unrooot can you try the latest commit and check if the server starts?

**Comment by unrooot** [comment]
sorry for the late reply - I was able to get it working with the latest commit, and this snippet:

```lua
vim.api.nvim_exec(
	[[
  autocmd BufRead,BufNewFile *.lua,*.luau set filetype=luau
]],
	false
)
```

thank you both for your help & work on this project!
